### ISSUE TITLE
İdeas

### ISSUE THREAD

**Issue by gokhanvaris** [LocaFi/bardly-mobile-app#7]
Bardly - AI Asistant

1- Ana ekranda Klavye inputu eziyor ekran patlıyor.
2- Ana ekrandaki topicler, yukarıdaki atılan ya da internetten bulunan popüler aramalar ile değiştirilebilir.
3- Explore kısmındaki başlıklar ve içerikleri arttırılabilir.
4- Explore kısmında card'ların butonlarına tıklandığında topic oluşturma ekranına gidilmeli.
5- Chat history kısmındaki silme butonu (rengi vb.) değiştirilebilir

**Comment by falniak95** [comment]
6- Chat ekranında geri tuşuna basıldığında uyarı verilecek.
